/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MoodAnalyser;

import org.junit.Test;
import org.junit.rules.ExpectedException;

import MoodAnalyser.MoodAnalysisException.ExceptionType;

import org.hamcrest.CoreMatchers;
import org.junit.Assert;

public class MoodAnalyserTest {
	@Test
	public void test_Sad_MoodAnalysis() {
		MoodAnalyser moodAnalyser = new MoodAnalyser("why am i sad?");
		String mood = moodAnalyser.analyseMood();
		Assert.assertThat(mood, CoreMatchers.is("SAD"));
	}

	@Test
	public void test_Happy_MoodAnalysis() {
		MoodAnalyser moodAnalyser = new MoodAnalyser("am i happy?");
		String mood = moodAnalyser.analyseMood();
		Assert.assertThat(mood, CoreMatchers.is("HAPPY"));
	}

	@Test
	public void Given_AnyAsMood_shouldReturnHappy() {
		MoodAnalyser moodAnalyser = new MoodAnalyser("i am in any mood?");
		String mood = moodAnalyser.analyseMood();
		Assert.assertThat(mood, CoreMatchers.is("HAPPY"));
	}
	
	@Test
	public void Given_NoMessage_shouldReturnSad() {
		MoodAnalyser moodAnalyser = new MoodAnalyser();
		String mood = moodAnalyser.analyseMood();
		Assert.assertThat(mood, CoreMatchers.is("SAD"));
	}

}
